---
  - name: Install nginx
    apt: name=nginx state=present update_cache=yes cache_valid_time=3600


  - name: create public_html directory
    file:
      path: /home/deploy/public_html
      state: directory
      recurse: yes
      owner: deploy
      group: deploy
      mode: 0755

  - name: remove default site
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: remove default site
    file: path=/etc/nginx/sites-available/default state=absent

  - name: configure nginx.conf
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644


  - name: configure vhosts
    template: src=vhost.conf dest=/etc/nginx/conf.d/{{domain_name}}.conf owner=root group=root mode=0644


  - name: config test and restart
    command: nginx -t -c /etc/nginx/nginx.conf
    ignore_errors: True
    register: result

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
    when: result|success

  - name: Update logroate for nginx
    copy: src=logrotate_nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644
