---
- hosts: devserver
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      
- include: base.yml
- include: users.yml
- include: webserver.yml
- include: database.yml
- include: php.yml
- include: solr.yml
- include: drupal.yml
