---
solr_workspace: /root

solr_create_user: true
solr_user: solr

solr_version: "6.6.0"
solr_mirror: "https://archive.apache.org/dist"
solr_filename: "solr-{{ solr_version }}"
solr_remove_cruft: true

solr_service_manage: true
solr_service_name: solr
solr_service_state: started

solr_install_dir: /opt
solr_install_path: "/opt/{{ solr_service_name }}"
solr_home: "/opt/{{ solr_service_name }}"
solr_connect_host: localhost
solr_port: "8983"

solr_xms: "128M"
solr_xmx: "256M"

solr_timezone: "PDT"

solr_cores:
  - collection1

solr_config_file: /etc/default/{{ solr_service_name }}.in.sh
